{
 "title": "Logs par service",
 "tags": [
  "logs",
  "grafana",
  "services",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Logs - PostgreSQL",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"postgres\"}"
    }
   ]
  },
  {
   "title": "Logs - TimescaleDB",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service=\"timescaledb\"}"
    }
   ]
  },
  {
   "title": "Logs - pgAdmin",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{service=\"pgadmin\"}"
    }
   ]
  },
  {
   "title": "Logs - Node-RED",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{service=\"nodered\"}"
    }
   ]
  },
  {
   "title": "Logs - Kafka",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "{service=\"kafka\"}"
    }
   ]
  },
  {
   "title": "Logs - Schema Registry",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "{service=\"schema-registry\"}"
    }
   ]
  },
  {
   "title": "Logs - AKHQ",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "{service=\"akhq\"}"
    }
   ]
  },
  {
   "title": "Logs - OPC UA Server",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "{service=\"opc-server\"}"
    }
   ]
  },
  {
   "title": "Logs - Loki",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "{service=\"loki\"}"
    }
   ]
  },
  {
   "title": "Logs - Alloy",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 144 },
   "targets": [
    {
     "expr": "{service=\"alloy\"}"
    }
   ]
  },
  {
   "title": "Logs - Grafana",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 160 },
   "targets": [
    {
     "expr": "{service=\"grafana\"}"
    }
   ]
  }
 ]
}